# day 1

In [25]:
data = parse.(Int, readlines("./day1/input"))
[(i, j, i*j) for i in data for j in data if i+j == 2020]

2-element Array{Tuple{Int64,Int64,Int64},1}:
 (1312, 708, 928896)
 (708, 1312, 928896)

In [24]:
[(i, j, k, i*j*k) for i in data for j in data for k in data if i+j+k == 2020]

6-element Array{NTuple{4,Int64},1}:
 (798, 664, 558, 295668576)
 (798, 558, 664, 295668576)
 (664, 798, 558, 295668576)
 (664, 558, 798, 295668576)
 (558, 798, 664, 295668576)
 (558, 664, 798, 295668576)

# day 2

In [61]:
input = split.(readlines("./day2/input"))
data = [vcat(parse.(Int, split(i[1], "-")), [i[2][1], i[3]]) for i in input]

1000-element Array{Array{Any,1},1}:
 [6, 7, 'w', "wwhmzwtwwk"]
 [10, 12, 'q', "qqqqqqqqqqqdqqq"]
 [16, 17, 'd', "ddddgdddddkddddsxddd"]
 [2, 4, 'q', "shbqwqpps"]
 [3, 4, 'q', "qkfq"]
 [2, 10, 'm', "bkdrmcfdhmr"]
 [13, 19, 's', "blccvhsgsnsssqszssm"]
 [1, 3, 'l', "qlxllhl"]
 [4, 6, 'h', "hhhqhhh"]
 [15, 17, 'l', "jrtllrlllllmmlllg"]
 [11, 12, 'n', "bnzlnnnnbnntnnnc"]
 [1, 7, 'p', "pppvppjppmptp"]
 [5, 6, 't', "tttnht"]
 ⋮
 [4, 13, 'j', "sjjjjjjjjjjjtjj"]
 [7, 8, 'r', "fztxkwhrrxnnn"]
 [5, 6, 'r', "rrqrrrr"]
 [1, 5, 'q', "qqqqvqqq"]
 [8, 14, 't', "ttvpttkptthtttrcj"]
 [2, 7, 'n', "znjqsvpstfjph"]
 [6, 7, 'l', "llllllnl"]
 [19, 20, 'c', "vwltcctcmcdccrqdccwc"]
 [4, 15, 'd', "bfkxfrsznfkdzpjmbp"]
 [12, 15, 'q', "qqqqqqqqqqqvqqqq"]
 [6, 10, 't', "tttttbttktt"]
 [1, 18, 'c', "ccdczcvccvclcccvkccb"]

In [72]:
sum([ i[1] <= count(c -> (c == i[3]), i[4]) <= i[2] for i in data])

477

In [76]:
sum([ xor(i[4][i[1]] == i[3], i[4][i[2]] == i[3]) for i in data])

686

# day 3

In [138]:
input = readlines("./day3/input")
data = input

function trees_hit(data::Array, right::Int=3, down::Int=1)::Int
    row = 1
    col = 1
    maxcols = length(data[1])
    maxrows = length(data)-1
    trees = 0

    for i = 1:maxrows/down
        row = row + down
        col = col + right
        if col > maxcols
            col = col - maxcols
        end
        if data[row][col] == '#'
            trees += 1
        end
    end
    return trees
end

res = 1
for (right, down) = [(1,1), (3,1), (5,1), (7,1), (1,2)]
    th = trees_hit(input, right, down)
    println(th)
    res *= th
end

res

79
234
72
91
48


5813773056

# day 4

In [52]:
input = replace.(split(read("./day4/input", String), "\n\n"), r"\n" => s" ")

data = [split.(pp) for pp in input]
data = [Dict(split.(pp, ":")) for pp in data]

valid_fields = ["hcl", "ecl", "pid", "cid", "iyr", "eyr", "hgt", "byr"]
sum([issubset(setdiff(valid_fields, keys(pp)), ["cid"]) for pp in data])

239

# day 5

In [173]:
input = readlines("./day5/input");

In [187]:
function parse_seat(seat_str, high='B')
    len = length(seat_str)
    coeffs = [c == high ? 1 : 0 for c in seat_str]
    return sum([c * 2^(len-pow) for (pow, c) in enumerate(coeffs)])
end

function seat_id(seat_str)
    return 8 * parse_seat(seat_str[1:7]) + parse_seat(seat_str[8:10], 'R')
    
end

seat_ids = seat_id.(input)
maximum(seat_ids)

938

In [188]:
function find_seat(seat_ids)
    i1 = 0
    for i in sort(seat_ids)
        if i == i1+2
            return i-1
        end
        i1 = i
    end
end
    
find_seat(seat_ids)

696

# day 6

In [76]:
using Test

function read_input(path)
    # chomp trailing \n, otherwise interpreted as empty set
    input = chomp(read(path, String))
    data = split(input, "\n\n")
    return data
end

function any_persons_answers(data)
    group_answers = delete!.(Set.(data), '\n')
    return group_answers
end

function all_persons_answers(data)
    person_answers = split.(data, '\n')
    every_person_answers = [ intersect(Set.(i)...) for i in person_answers ]
    return every_person_answers
end

sum_count(answers) = sum(length.(answers))

@test sum_count(any_persons_answers(read_input("./day6/test"))) == 11
@test sum_count(all_persons_answers(read_input("./day6/test"))) == 6

data = read_input("./day6/input")


print("$(sum_count(any_persons_answers(data))), $(sum_count(all_persons_answers(data)))")

6170, 2947

# day 7

# day 8

In [41]:
mutable struct ProgramInstance
    code::Array{Any, 2}
    acc::Int
    idx::Int
    idx_history::Array{Int, 1}
    ProgramInstance(code, acc, idx) = new(code, acc, idx, [idx])
end

function Base.show(io::IO, prog::ProgramInstance)
   print("idx=$(prog.idx), acc=$(prog.acc)") 
end


function read_input(path)
    input = readlines(path)
    code = split.(input)
    code = Array{Any, 2}(hcat(split.(input)...))
    code[2,:] = parse.(Int, code[2,:])
    return permutedims(code)
end

function parse_code(prog::ProgramInstance)
    cmd, val = prog.code[prog.idx, :]
    if cmd == "jmp"
        prog.idx += val
    elseif cmd == "acc"
        prog.acc += val
        prog.idx += 1
    elseif cmd == "nop"
        prog.idx += 1
    end
#     return prog
end

function debug(prog)
    if prog.idx in Set(prog.idx_history)
#             print("acc=$acc, $(code[idx,1])=$(code[idx,2]), $idx, $idx_history")
        println("Infinite Loop. acc=$(prog.acc), idx=$(prog.idx)")
        return 1
    elseif prog.idx <= 0
        println("Negative index. acc=$(prog.acc), idx=$(prog.idx)")
        return 1
    elseif prog.idx > size(code, 1)
        println("Success! acc=$(prog.acc), idx=$(prog.idx)")
        return 0
    end
    return -1
end

function run(code)
    prog = ProgramInstance(code, 0, 1)
    
    exit_code = -1
    while true
        parse_code(prog)
        exit_code = debug(prog)
        
        if exit_code >= 0
            break
        end

        push!(prog.idx_history, prog.idx)
    end
    
    return exit_code, prog.acc
end

function modify_code(code, idx, to="jmp")
    code_copy = copy(code)
    code_copy[idx, 1] = to
    return code_copy
end

code = read_input("./day8/test")
run(code)

Infinite Loop. acc=5, idx=2


(1, 5)

In [46]:
code = read_input("./day8/input")

exit_code = -1
acc = 0
for idx in 1:size(code,1)
    if code[idx, 1] == "nop"
        exit_code, acc = run(modify_code(code, idx, "jmp"))
    elseif code[idx, 1] == "jmp"
        exit_code, acc = run(modify_code(code, idx, "nop"))
    end
    if exit_code == 0
        println(acc)
        break
    end
end

Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1972, idx=74
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1890, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1800, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1016, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1367, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1556, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=958, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=975, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=1262, idx=608
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop. acc=2014, idx=375
Infinite Loop

# day 9

In [111]:
function validate(data, idx, range)
    data_range = data[idx-range:idx-1]
    resid = data[idx] .- data_range
    is_not_used_twice = resid .!= data_range
    is_in_range = [ r in Set(data_range) for r in resid ] # afaik no broadcasting for 'in'
    return |((is_not_used_twice .& is_in_range)...)
end

function find_invalid(data, range)
    for idx in (range+1):length(data)
        if validate(input, idx, range) == false
            invalid = input[idx]
            return idx, invalid
        end
    end
end

find_invalid(parse.(Int, readlines("./day9/input")), 25)

(560, 90433990)

In [110]:
function get_sum_range(data, idx, thresh)
    total = cumsum(data) .- sum(input[1:idx])
    sum_range = data[findall(0 .<= total .<= thresh)]
    return sum_range, sum(sum_range)
end

input = parse.(Int, readlines("./day9/input"))
idx, thresh = find_invalid(input, 25)


for i in 1:idx-1
    sum_range, sum_sum_range = get_sum_range(input, i, thresh)
    if sum_sum_range == thresh
        return sum_range, maximum(sum_range) + minimum(sum_range)
    end
end

([3289338, 5179176, 4759952, 5413470, 8402308, 4463250, 5358204, 5385482, 4715571, 5141223, 4879861, 5096842, 5206454, 6345865, 5288410, 5946272, 5562312], 11691646)

# day 10

In [138]:
using StatsBase

input = parse.(Int, readlines("./day10/input"))
append!(input, [0, maximum(input)+3])
data = sort(input)
data_diff = data[2:end] - data[1:end-1]
occurences = countmap(data_diff)
occurences[1] * occurences[3]

2343

In [144]:
using Combinatorics
using IterTools

function perm_length(len)
    """only works for step sizes up to 3"""
    choosearr = vcat(Int.(ones(len)), Int.(2 * ones(Int((len-mod(len,2))/2))), Int.(3 * ones(Int((len-mod(len,3))/3))))

    subs = unique([i for i in subsets(choosearr) if sum(i) == len])
    return size(unique([i for perm in permutations.(subs) for i in perm]), 1)
end

occ, occ_len = rle(data_diff) # run-length-encoding

*([perm_length(occ_len[i]) for (i, o) in enumerate(occ) if o == 1]...)

31581162962944